services:
  rest-api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    env_file:
      - './backend/.env'
    ports:
      - '4200:80'
    volumes:
      - ./backend:/usr/src/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    env_file:
      - './frontend/.env'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - rest-api
