services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - '.env'
    volumes:
      - static-files:/usr/src/app/static
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  proxy-server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '4200:80'
    volumes:
      - static-files:/usr/src/static
    links:
      - django
    depends_on:
      - django
volumes:
  static-files:
