# Generated by Django 4.1.7 on 2023-04-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('subjects', '0001_initial'),
        ('groups', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSchedule',
            new_name='ClassesSchedule',
        ),
        migrations.RenameModel(
            old_name='ClassSchedulePeriod',
            new_name='ClassesSchedulePeriod',
        ),
    ]
