# Generated by Django 4.1.7 on 2023-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_classschedule_classesschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesscheduleperiod',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classesscheduleperiod',
            name='cabinet',
            field=models.CharField(max_length=255),
        ),
    ]
