# Generated by Django 4.1.7 on 2023-03-20 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='Группа может иметь только одно расписание на один день',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='group_slug',
            new_name='group_id',
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timetableperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(models.F('group_id'), models.F('date'), name='Группа может иметь только одно расписание на один день'),
        ),
    ]
