# Generated by Django 4.1.7 on 2023-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_alter_timetableperiod_timetable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='Группа может иметь только одно расписание на один день',
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(models.F('group'), models.F('date'), name='Группа может иметь только одно расписание на один день'),
        ),
    ]
