# Generated by Django 4.1.7 on 2023-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_remove_timetable_группа может иметь только одно расписание на один день_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='note',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
