# Generated by Django 4.1.7 on 2023-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bellsperiod',
            constraint=models.UniqueConstraint(models.F('bells'), models.F('index'), name='Номер звонка на пару должен быть уникальным'),
        ),
    ]
