# Generated by Django 4.1.7 on 2023-05-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesscheduleperiod',
            name='cabinet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
