# Generated by Django 4.1.7 on 2023-07-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('changes', 'Changes'), ('main', 'Main')], max_length=7)),
                ('variant', models.CharField(choices=[('normal', 'Normal'), ('reduced', 'Reduced')], max_length=7)),
                ('week_day', models.CharField(blank=True, choices=[('ПН', 'Monday'), ('ВТ', 'Tuesday'), ('СР', 'Wednesday'), ('ЧТ', 'Thursday'), ('ПТ', 'Friday'), ('СБ', 'Saturday'), ('ВС', 'Sunday')], max_length=2, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BellsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('has_break', models.BooleanField()),
                ('period_from', models.DurationField(db_column='from')),
                ('period_to', models.DurationField(db_column='to')),
                ('period_from_after', models.DurationField(blank=True, db_column='from_after', null=True)),
                ('period_to_after', models.DurationField(blank=True, db_column='to_after', null=True)),
                ('bells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='bells.bells')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddConstraint(
            model_name='bells',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'main'), ('week_day__isnull', False)), models.Q(('type', 'changes'), ('date__isnull', False)), _connector='OR'), name='Целостность расписания звонков в зависимости от состояния'),
        ),
        migrations.AddConstraint(
            model_name='bells',
            constraint=models.UniqueConstraint(models.F('variant'), models.F('week_day'), name='Одно расписание на один день недели'),
        ),
        migrations.AddConstraint(
            model_name='bells',
            constraint=models.UniqueConstraint(models.F('variant'), models.F('date'), name='Одно расписание на одну дату'),
        ),
        migrations.AddConstraint(
            model_name='bellsperiod',
            constraint=models.CheckConstraint(check=models.Q(('has_break', True), ('period_from_after__isnull', False), ('period_to_after__isnull', False)), name='Наличие двух дополнительных полей в случае, если указано has_break'),
        ),
    ]
