# Generated by Django 4.1.7 on 2023-05-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('changes', 'Changes'), ('main', 'Main')], max_length=7)),
                ('view', models.CharField(choices=[('table', 'Table'), ('message', 'Message')], max_length=7)),
                ('date', models.DateField(blank=True, null=True)),
                ('week_day', models.CharField(blank=True, choices=[('ПН', 'Monday'), ('ВТ', 'Tuesday'), ('СР', 'Wednesday'), ('ЧТ', 'Thursday'), ('ПТ', 'Friday'), ('СБ', 'Saturday'), ('ВС', 'Sunday')], max_length=2, null=True)),
                ('week_type', models.CharField(blank=True, choices=[('ЗНАМ', 'Denominator'), ('ЧИСЛ', 'Numerator')], max_length=4, null=True)),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='ClassesSchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('cabinet', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(to='teachers.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='classes.classesschedule')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddConstraint(
            model_name='classesscheduleperiod',
            constraint=models.UniqueConstraint(models.F('timetable'), models.F('index'), name='Номер пары должен быть уникальным'),
        ),
        migrations.AddConstraint(
            model_name='classesschedule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'main'), ('view', 'table'), ('week_day__isnull', False), ('week_type__isnull', False)), models.Q(('type', 'changes'), ('date__isnull', False)), _connector='OR'), name='Целостность данных в зависимости от состояния'),
        ),
        migrations.AddConstraint(
            model_name='classesschedule',
            constraint=models.UniqueConstraint(models.F('group'), models.F('date'), condition=models.Q(('type', 'changes')), name='Группа может иметь только одно изменение в расписании на один день'),
        ),
        migrations.AddConstraint(
            model_name='classesschedule',
            constraint=models.UniqueConstraint(models.F('group'), models.F('week_type'), models.F('week_day'), condition=models.Q(('type', 'main')), name='Группа может иметь только одно расписание на один день'),
        ),
    ]
