# Generated by Django 4.1.7 on 2023-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classesscheduleperiod_cabinet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classesschedule',
            name='Целостность данных в зависимости от состояния',
        ),
        migrations.AddConstraint(
            model_name='classesschedule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'main'), ('view', 'table'), ('week_day__isnull', False), ('week_type__isnull', False)), models.Q(('type', 'changes'), ('date__isnull', False)), _connector='OR'), name='Целостность расписания занятий в зависимости от состояния'),
        ),
    ]
