# Generated by Django 4.1.7 on 2023-03-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0002_alter_teacher_subjects'),
        ('subjects', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_main', models.BooleanField()),
                ('group_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(max_length=55)),
                ('index', models.PositiveSmallIntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(to='teachers.teacher')),
                ('timetable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.UniqueConstraint(models.F('timetable_id'), models.F('index'), name='Номер пары должен быть уникальным'),
        ),
    ]
