# Generated by Django 4.1.7 on 2023-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(models.F('group_slug'), models.F('date'), name='Группа может иметь только одно расписание на один день'),
        ),
    ]
